import type { LivePlatformConfig } from '../live/config'

export const DOUYU_PLATFORM_CONFIG: LivePlatformConfig = {
  name: '斗鱼直播',
  maxLength: 500,
  chatRoots: [
    '#js-barrage-container',
    '#js-barrage-list',
    '.Barrage-container',
    '.Barrage-main',
    '.Barrage-list',
    '.layout-Player-chat',
    "[class*='Barrage-container']",
  ],
  videoRoots: [
    '#js-player-main',
    '#js-player-video',
    '.layout-Player-video',
    '.layout-Player-barrageStage',
    '.layout-Player-barrage',
    "[class*='player__']",
    "[class*='video__']",
  ],
  overlayMessages: [
    "[class*='danmuItem-']",
    "[data-comment-uuid][class*='danmu']",
    "[class*='danmu-item' i]",
    "[class*='danmuItem']",
  ],
  messages: [
    '.Barrage-listItem:has(.Barrage-nickName):has(.Barrage-content)',
    '#js-barrage-list > li:has([data-chatid])',
    "[class*='Barrage-listItem']:has([class*='Barrage-content'])",
    '[data-chatid]',
  ],
  messageText: [
    '.Barrage-content',
    '[data-chatid]',
    "[class*='text-']",
    "[class*='danmuText-']",
    "[class*='message-content' i]",
  ],
  userNames: [
    '.Barrage-nickName:not(.is-colon)',
    '.js-nick:not(.is-colon)',
    '[data-uid][title]:not(.is-colon)',
    "[class*='hostname-']",
    "[class*='nickName']",
    '[data-username]',
    '[data-user-name]',
    '[data-nickname]',
    '[data-author-name]',
  ],
  inputs: [
    ".ChatSend-txt[contenteditable='true']",
    "[contenteditable='true'][data-placeholder*='聊天内容']",
    "[class*='inputView-'][placeholder*='发送弹幕']",
    "input[placeholder*='发送弹幕']",
    "textarea[placeholder*='发送弹幕']",
    "[class*='fullScreenSendor-'] input",
  ],
  sendButtons: [
    '.ChatSend-button',
    "[class*='sendDanmu-']",
    "button[title='发送']",
    '.ChatSend button',
    "button[class*='send' i]",
  ],
}
